env:
  TERM: xterm-256color
window:
  dynamic_padding: true
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 12
  use_thin_strokes: true
# Colors (Dracula PRO)
colors:
  # Default colors
  primary:
    background: '0x22212c'
    foreground: '0xf8f8f2'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x454158'
    cursor: '0xf8f8f2'

  # Selection colors
  #
  # Colors which should be used to draw the selection area. If selection
  # background is unset, selection color will be the inverse of the cell colors.
  # If only text is unset the cell text color will remain the same.
  selection:
    text: '0xf8f8f2'
    background: '0x454158'

  # Normal colors
  normal:
    black: '0x22212c'
    red: '0xff9580'
    green: '0x8aff80'
    yellow: '0xffff80'
    blue: '0x9580ff'
    magenta: '0xff80bf'
    cyan: '0x80ffea'
    white: '0xf8f8f2'

  # Bright colors
  bright:
    black: '0x22212c'
    red: '0xffaa99'
    green: '0xa2ff99'
    yellow: '0xffff99'
    blue: '0xaa99ff'
    magenta: '0xff99cc'
    cyan: '0x99ffee'
    white: '0xffffff'
cursor:
  style:
    shape: Block
  unfocused_hollow: true
shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -c
    - /opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux
  render_timer: false
  persistent_logging: false
  log_level: Off
  print_events: false
key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
