env:
  TERM: xterm-256color

window:
  dynamic_padding: true

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 13
  use_thin_strokes: true

colors:
  primary:
    background: '#22212c'
    foreground: '#f8f8f2'

    dim_foreground: '#9a9a9a'
    bright_foreground: '#ffffff'

  cursor:
    text: '#454158'
    cursor: '#f8f8f2'

  selection:
    text: '#f8f8f2'
    background: '#454158'

  normal:
    black: '#22212c'
    red: '#ff9580'
    green: '#8aff80'
    yellow: '#ffff80'
    blue: '#9580ff'
    magenta: '#ff80bf'
    cyan: '#80ffea'
    white: '#f8f8f2'

  bright:
    black: '#6272a4'
    red: '#ffaa99'
    green: '#a2ff99'
    yellow: '#ffff99'
    blue: '#aa99ff'
    magenta: '#ff99cc'
    cyan: '#99ffee'
    white: '#ffffff'

cursor:
  style:
    shape: Block
  unfocused_hollow: true

shell:
  program: /opt/homebrew/bin/zsh
  render_timer: false
  persistent_logging: false
  log_level: Off
  print_events: false

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
