env:
  TERM: xterm-256color
window:
  dynamic_padding: true
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 12
  use_thin_strokes: true
colors:
  author: ""
  primary:
    background: "#101010"
    foreground: "#00ee00"
  cursor:
    text: "#101010"
    cursor: "#008c00"
  normal:
    black: "#1c1c1c"
    red: "#d81860"
    green: "#60ff60"
    yellow: "#f9fd75"
    blue: "#4695c8"
    magenta: "#a78edb"
    cyan: "#43afce"
    white: "#f3ebe2"
  bright:
    black: "#4d4d4d"
    red: "#f00060"
    green: "#70ff70"
    yellow: "#f9fd80"
    blue: "#5a9dc8"
    magenta: "#b29fdb"
    cyan: "#69b8ce"
    white: "#eeeeee"
cursor:
  style:
    shape: Block
  unfocused_hollow: true
shell:
  program: /opt/homebrew/bin/ion
  args:
    - -c
    - /opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux
  render_timer: false
  persistent_logging: false
  log_level: Off
  print_events: false
key_bindings:
  - key: N
    mods: Command
    command:
      program: open
      args:
        - -n
        - /Applications/Alacritty.app
